const NEW_MESSAGE = 'NEW_MESSAGE';
const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT';
const NEW_REQUEST = 'NEW_REQUEST';
const START_TYPING = 'START_TYPING';
const STOP_TYPING = 'STOP_TYPING';
const ALERT = 'ALERT';
export {
  NEW_MESSAGE,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  START_TYPING,
  STOP_TYPING,
  ALERT,
};
